services:
  bookservice:
    image: bookservice
    build:
      context: .
      dockerfile: BookService/Dockerfile

  orderservice:
    image: orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
